version: 2
jobs:
  # job name is "one:"
  build:
    docker:
      #- image: microsoft/dotnet:2.1-runtime
      - image: microsoft/dotnet:2.1.300-preview2-sdk-alpine
    steps:
      - checkout
      - run: find
      - run: dotnet restore
      #- run:  
          # name: Build
          # command: dotnet build
      
