version: 2
jobs:
  # job name is "one:"
  build:
    docker:
      - image: microsoft/dotnet:2.1-runtime
    steps:
      - checkout
      - run: echo "A first hello, job one"
      - run: dotnet build
      - run: dotnet run
      
